services:
  - type: worker
    name: slack-bot-dona-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    plan: starter  # $7/month - upgrade from free tier for better reliability
    
    # Environment variables - set these in Render Dashboard for security
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false  # Will be set manually for security
      - key: SLACK_APP_TOKEN
        sync: false  # Will be set manually for security
      - key: OPENROUTER_API_KEY
        sync: false  # Will be set manually for security
      
      # Bot configuration - safe to include in code
      - key: LLM_PROVIDER
        value: openrouter
      - key: OPENROUTER_MODEL
        value: meta-llama/llama-3.3-8b-instruct:free
      - key: OPENROUTER_MAX_TOKENS
        value: "1000"
      - key: OPENROUTER_TEMPERATURE
        value: "0.7"
      - key: OPENROUTER_SITE_URL
        value: https://slack.com
      - key: OPENROUTER_APP_NAME
        value: Dona Bot
      - key: BOT_SYSTEM_PROMPT
        value: "Eres Dona, un asistente útil y amigable en Slack para el equipo de Autonomos. Eres profesional pero amigable, respondes en el mismo idioma que te hablan, y usas emojis de forma moderada para ser más amigable."
      - key: LOG_LEVEL
        value: INFO  # Less verbose for production
      - key: BOT_NAME
        value: DonaBot
      
    # Health checks and auto-restart configuration
    healthCheckPath: null  # Background worker doesn't need HTTP health checks
    
    # Resource limits (optional, for cost control)
    disk:
      name: slack-bot-data
      sizeGB: 1
      mountPath: /opt/render/project/data